FROM python:3.7-stretch

RUN apt-get -y update
COPY requirements.txt ./
COPY Worker ./
RUN  apt-get -y install python3
RUN  apt-get -y install python3-pip
RUN  curl -sSL https://get.docker.com/ | sh
RUN  pip3 install kazoo
RUN  pip3 install gevent
RUN  pip3 install pika --upgrade
RUN  pip3 install mysql-connector
RUN  pip3 install docker
RUN  pip3 install --no-cache-dir -r requirements.txt


